DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
    `uid` INT NOT NULL AUTO_INCREMENT,
    `firstName` VARCHAR(30) NOT NULL DEFAULT '',
    `lastName` VARCHAR(30) NOT NULL DEFAULT '',
    `login` VARCHAR(20) NOT NULL,
    `password` VARCHAR(70) NOT NULL,
    `dateFirstOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dateLastOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`uid`) 
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `CONTACTS`;

CREATE TABLE `CONTACTS` (
    `cid` INT NOT NULL AUTO_INCREMENT,
    `uid` INT NOT NULL,
    `firstName` VARCHAR(30) NOT NULL DEFAULT '',
    `lastName` VARCHAR(30) NOT NULL DEFAULT '',
    `phone` VARCHAR(15) NOT NULL DEFAULT '',
    `email` VARCHAR(20) NOT NULL DEFAULT '',
    `address` VARCHAR(100) NOT NULL DEFAULT '',
    `city` VARCHAR(20) NOT NULL DEFAULT '',
    `state` VARCHAR(20) NOT NULL DEFAULT '',
    `zip` VARCHAR(7) NOT NULL DEFAULT '',
    `dateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `dateLastUpdated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`cid`)
) ENGINE = InnoDB;